# Site settings
title:          Finnq 기술블로그
description:    "Finnq Technical Blog"
url:            "https://techfinnq.github.io"
lang: ko

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Finnq Developers
  url:          https://www.finnq.com
  email:        finnq@finnq.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:       #

# Custom settings